import os

class Config:
    TELEGRAM_TOKEN = os.environ.get("TELEGRAM_TOKEN", "DEFAULT_TOKEN_NOT_SET")
    print(f"Config: TELEGRAM_TOKEN = {TELEGRAM_TOKEN}")
    GOOGLE_APPLICATION_CREDENTIALS = os.environ.get("GOOGLE_APPLICATION_CREDENTIALS", "DEFAULT_TOKEN_NOT_SET")
    WATCHLIST_SHEET_ID = "1EWVVCYC5EbYzx3jIFhwthdTJxyNvWdz57kzX-DRwwn0"
    ANTHROPIC_API_KEY = os.environ.get("ANTHROPIC_API_KEY", "DEFAULT_TOKEN_NOT_SET")
    WEBHOOK_URL = os.environ.get("MAKE_WEBHOOK", "DEFAULT_TOKEN_NOT_SET")
