import os

class Config:
    TELEGRAM_TOKEN = os.environ.get("TELEGRAM_TOKEN", "DEFAULT_TOKEN_NOT_SET")
    print(f"Config: TELEGRAM_TOKEN = {TELEGRAM_TOKEN}")
    GOOGLE_APPLICATION_CREDENTIALS = os.environ.get("GOOGLE_CREDENTIALS", "DEFAULT_TOKEN_NOT_SET")
    WATCHLIST_SHEET_ID = "1EWVVCYC5EbYzx3jIFhwthdTJxyNvWdz57kzX-DRwwn0"
